// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionController from "./action_controller"
application.register("action", ActionController)

import BadgeController from "./badge_controller"
application.register("badge", BadgeController)

import CalculateController from "./calculate_controller"
application.register("calculate", CalculateController)

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import CompanyController from "./company_controller"
application.register("company", CompanyController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import ExportController from "./export_controller"
application.register("export", ExportController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageController from "./image_controller"
application.register("image", ImageController)

import IncaseController from "./incase_controller"
application.register("incase", IncaseController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import ProductController from "./product_controller"
application.register("product", ProductController)

import PropController from "./prop_controller"
application.register("prop", PropController)

import SelectallController from "./selectall_controller"
application.register("selectall", SelectallController)

import SlimselectController from "./slimselect_controller"
application.register("slimselect", SlimselectController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TemplateController from "./template_controller"
application.register("template", TemplateController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)

import UserController from "./user_controller"
application.register("user", UserController)
