// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PropController from "./prop_controller"
application.register("prop", PropController)

import SlimSelectController from "./slimselect_controller"
application.register("slimselect", SlimSelectController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ExportController from "./export_controller"
application.register("export", ExportController)

import CompanyController from "./company_controller"
application.register("company", CompanyController)