export:
  cron: "0 * * * *" #every hour
  class: "ExportScheduler"
  queue: "export"
log_files:
  cron: "00 23 * * *" #at 23-00
  class: "CreateLogFilesScheduler"
  queue: "default"
delete_unattached_blobs_every_day:
  cron: "15 23 * * *" #at 23-15
  class: "DeleteUnattachedBlobsScheduler"
  queue: "default"
import_product:
  cron: "00 06 * * *" #at 06-00
  class: "ImportProductScheduler"
  queue: "import_product"