:concurrency: 5

:queues:
    - default
    - mailers
    - export
    - print
    - attach_image
    - product_content_save
    - incase_import
    - import_product
    - bulk_delete
    - active_storage_analysis
    - active_storage_purge
:scheduler:
  :dynamic: true


development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20