:concurrency: 5

:queues:
    - default
    - mailers
    - export
    - print
    - attach_image
:scheduler:
  :dynamic: true


development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20 